export const ADD_PRODUCT = "ADD_PRODUCT";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const SET_CUSTOMERS = "SET_CUSTOMERS";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

export const SET_EMPLOYEE = "SET_EMPLOYEE";

export const CHANGE_FORM_STATE = "CHANGE_FORM_STATE ";
export const CHANGE_MODAL_STATE = "CHANGE_MODAL_STATE";