export {addProduct,setProducts,deleteProduct,changeFormState,updateProduct,changeModalState} from './products'
export {addCategory,setCategories,deleteCategory,changeFormStateCategory,updateCategory} from './categories'
export {addCustomer,setCustomers,deleteCustomer,changeFormStateCustomer,updateCustomer,updateTotalAmountOfCustomer,incrementTotalAmountOfCustomer} from './customers'
export {addOrder,setOrders,changeFormStateOrder,updateOrder,setTotalAmount,incrementTotalAmount,updateTotalAmount} from './orders'
export {addEmployee} from './login'